LWIS: fix -Wdeprecated-non-prototype
Fixes the warnings observed when upgrading the toolchain:

lwis/lwis_device.c:1080:40: error: a function declaration without a
prototype is deprecated in all versions of C
[-Werror,-Wstrict-prototypes]
static struct lwis_device *find_top_dev()
                                       ^
                                        void

In file included from lwis/lwis_event.c:19:
lwis/lwis_util.h:62:36: error: a function declaration without a
prototype is deprecated in all versions of C
[-Werror,-Wstrict-prototypes]
static inline ktime_t lwis_get_time()
                                   ^
                                    void

Bug: 236798112
Signed-off-by: Nick Desaulniers <ndesaulniers@google.com>
Change-Id: I6fcae78fb780141a08ee38cf7affd686a169056b